server:
  port: 7914

spring:
  cloud:
    gateway:
      routes:

        - id: passenger-service
          uri: lb://PASSENGER-SERVICE
          predicates:
            - Path=/passenger/**

        - id: carrentals-service
          uri: lb://CARRENTALS-SERVICE
          predicates:
            - Path=/rental/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7910/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
